### ISSUE TITLE
Postgres connection with Postgres user

### ISSUE THREAD

**Issue by chadyred** [Bonitasoft-Community/docker_bonita#2]
Hello ! 

I have a connection problem here : 

```
psql -U postgres -h 172.17.0.3 -p 5432 -d postgres -t -A -c 'SELECT 1 FROM pg_roles WHERE rolname='\''bonita'\'''
bonita_1   | + grep -q 1
postgres_1 | FATAL:  password authentication failed for user "postgres"
```

Bad idea: docker create with postgres user but no password is required for it...It has no password by default.

```
postgres:
    image: postgres:9.3
    environment:
        - POSTGRES_PASSWORD=bonita
        - POSTGRES_USER=bonita
        - POSTGRES_DB=bonitasoft

        - BIZ_DB_NAME=bonitabz_db
        - BIZ_DB_USER=bonitabz
        - BIZ_DB_PASS=bonitabz
    volumes: 
        - "/data/bonita/postgres:/var/lib/postgresql/data:rw"
        - "./docker/postgres/custom/docker-entrypoint.sh:/docker-entrypoint-initdb.d/docker-entrypoint.sh:rw"

```
